include:
    - project: "epi2melabs/ci-templates"
      file: "push-github.yaml"
    - project: "epi2melabs/ci-templates"
      file: "push-conda.yaml"
    - project: "epi2melabs/ci-templates"
      file: "snippets.yaml"

image: ${UBUNTUIMAGE}:20.04

.prep-image: &prep-image |
    export DEBIAN_FRONTEND=noninteractive
    apt update -qq
    apt install -y --no-install-recommends make wget python3-all-dev python3-venv 


stages:
    - test
    - build
    - prerelease
    - release
    - postrelease

deploy-checks:
    stage: prerelease
    script:
        - !reference [.check, python-version]
        - !reference [.check, changelog]
    rules:
        - if: '$CI_COMMIT_TAG =~ /^v[[:digit:]]+\.[[:digit:]]+\.[[:digit:]]+$/'

test:
    stage: test
    script:
        - *prep-image
        - make test
        - make docs
        - make sdist
    artifacts:
        paths:
            - dist/*.tar.gz

conda:
    variables:
        PACKAGE_ARCH: "noarch"
    tags:
        - large_ram
    extends:
        - .deploy-conda
    before_script:
        - *prep-image
        - export CONDA_PKG=${CI_PROJECT_NAME}
        - export CONDA_PKG_VERSION=${CI_COMMIT_TAG/v/}
        - cd conda
